# import tkinter as tk
# root=tk.Tk()
# root.geometry("1080x1350")
# root.title("Window")
# label=tk.Label(root,text="Hello world",font=('Poppins',18))
# label.pack(padx=40,pady=0)
# textbox= tk.Text(root,height=5,font=('Arial',16))
# textbox.pack(pady=100)
# myentry=tk.Entry(root)
# myentry.pack(pady=110)
# root.mainloop()
import tkinter as tk
root=tk.Tk()
root.geometry("1080x1080")
root.title("Button frame")
label=tk.Label(root,text="This is a button frame",font=("Ariel",18))
label.pack()
frame=tk.Frame(root)
frame.columnconfigure(0,weight=1)
frame.columnconfigure(1,weight=1)
frame.columnconfigure(2,weight=1)

bt1=tk.Button(frame,text="1")
bt1.grid(row=0,column=0,sticky=tk.W+tk.E)
bt1=tk.Button(frame,text="2")
bt1.grid(row=0,column=1,sticky=tk.W+tk.E)
bt1=tk.Button(frame,text="3")
bt1.grid(row=0,column=2,sticky=tk.W+tk.E)

frame.pack(fill='x')
root.mainloop()